version: '3.8'


services:
  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8005
    volumes:
      - .:/home/app/web/staticfiles
      - .:/home/app/web/mediafiles
    expose:
      - 8005